version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    # Volume shall be added to keep data consistency
    environment:
      - POSTGRES_PASSWORD=hajshajskh1212
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tours-db

  tours-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=postgresql://postgres:hajshajskh1212@postgres:5432/tours-db?schema=public&connection_limit=5&socket_timeout=3
      - PORT=3001
      - ORIGINS=http://localhost:3000,http://localhost:3001
