version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    # Volume shall be added to keep data consistency
    environment:
      - POSTGRES_PASSWORD=hajshajskh1212
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tours-db

  tours-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=postgresql://postgres:hajshajskh1212@postgres:5432/tours-db?schema=public&connection_limit=5&socket_timeout=3
      - PORT=3001
      - ORIGINS=http://localhost:3000,http://localhost:3001

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    # depends_on:
    #  - tours-api

  grafana:
    image: grafana/grafana:latest
    ports:
      - 4000:3000
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki:2.9.3
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

volumes:
  grafana_data:
  loki_data:
